name: FreeRTOS-Kernel Demos
on: [push, pull_request]

jobs:
  ARM-GCC:
    name: GNU ARM Toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the FreeRTOS/FreeRTOS Repository
        uses: actions/checkout@v2
        with:
          ref: main
          repository: FreeRTOS/FreeRTOS
          submodules: 'recursive'
          fetch-depth: 1

      # Checkout user pull request changes
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          path: ./FreeRTOS/Source

      - name: Install GNU ARM Toolchain
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc-arm-none-eabi build-essential cmake git ninja-build python3-minimal

      - name: Build CORTEX_MPU_M3_MPS2_QEMU_GCC Demo
        shell: bash
        working-directory: FreeRTOS/Demo/CORTEX_MPU_M3_MPS2_QEMU_GCC
        run: make -j

      - name: Upload CORTEX_MPU_M3_MPS2_QEMU_GCC Demo to Loci
        uses: auroralabs-loci/loci-action@v1
        env:
          LOCI_BACKEND_URL: '${{ vars.LOCI_BACKEND_URL }}'
          LOCI_API_KEY: '${{ secrets.LOCI_API_KEY }}'
        with:
          mode: upload
          binaries: FreeRTOS/Demo/CORTEX_MPU_M3_MPS2_QEMU_GCC/build/RTOSDemo.axf
          project: FreeRTOS-Kernel
